spring:
  data.rest.base-path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: trace